[package]
name = "whistle-tls"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CA 生成与动态证书签发、rustls 集成（HTTPS MITM）"

[dependencies]
rustls.workspace = true
rustls-pki-types.workspace = true
rcgen.workspace = true
time.workspace = true
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
x509-parser = "0.16"
